# Generated by Django 3.0.14 on 2022-05-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deparment',
            new_name='department',
        ),
    ]
